version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: u_mongo
      MONGO_INITDB_ROOT_PASSWORD: p_mongo
    networks:
      - database
    ports:
      - 27017:27017